<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\SmartHouseManagment.AppCore\SmartHouseManagment.AppCore.csproj"/>
        <ProjectReference Include="..\SmartHouseManagment.Domain\SmartHouseManagment.Domain.csproj"/>
    </ItemGroup>
    
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.10" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.16" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.16" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.16">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.16" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.16">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
      <PackageReference Include="Scrutor" Version="7.0.0" />
      <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.7" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.7" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.7" />
    </ItemGroup>

</Project>
