<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\SmartHouseManagment.AppCore\SmartHouseManagment.AppCore.csproj"/>
        <ProjectReference Include="..\SmartHouseManagment.Domain\SmartHouseManagment.Domain.csproj"/>
    </ItemGroup>
    
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Extensions\" />
      <Folder Include="Repositories\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.16" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.16" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.16" />
    </ItemGroup>

</Project>
